app:
  jwt:
    # Génère un secret base64 (256 bits) une fois, p.ex. via `openssl rand -base64 32`
    secret: "yQ3rRr2h4qf2Yl9y0P0b3bK8vQ6Q3y7r2c7mZ2b0s9d1m4n5o6p7q8r9s0t1u2v3"
    expiration-ms: 86400000  # 24h

spring:
  datasource:
    url: jdbc:h2:mem:pit;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
