-- USERS
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(32) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- PLACE / PLACES : choisis **le même nom** que dans @Table de ton entité
-- Si tu as @Table(name = "places"), utilise "places". Sinon, garde "place".
CREATE TABLE places (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(1000),
                       lat DOUBLE PRECISION NOT NULL,
                       lng DOUBLE PRECISION NOT NULL,
                       status VARCHAR(32) NOT NULL,     -- PlaceStatus (PENDING/APPROVED/REJECTED)
                       created_by BIGINT NOT NULL,
                       CONSTRAINT fk_place_user FOREIGN KEY (created_by) REFERENCES users(id)
);
