-- USERS
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(32) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- PLACES table definition must align with the @Table mapping on the entity.
-- Keep the same table name configured in the JPA annotation.
CREATE TABLE places (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       description VARCHAR(1000),
                       lat DOUBLE PRECISION NOT NULL,
                       lng DOUBLE PRECISION NOT NULL,
                       status VARCHAR(32) NOT NULL,     -- PlaceStatus (PENDING/APPROVED/REJECTED)
                       created_by BIGINT NOT NULL,
                       CONSTRAINT fk_place_user FOREIGN KEY (created_by) REFERENCES users(id)
);
